version: '3'

services:
  magento1:
    build: ./magento
    ports:
      - 9095:80
      - 9096:443
    depends_on:
      - db
    env_file:
      - .env
    environment:
      BASE_URL: https://m1.com/
    volumes:
      - ./src:/var/www/html
    networks:
      webnet:
        aliases:
          - m1.com

  db:
    build: ./data
    ports:
      - 3308:3306
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9097:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    links:
      - db
    depends_on:
      - db
    networks:
      - webnet
networks:
  webnet:
